---
- hosts: REDHAT
  remote_user: root
  tasks: 
    - name: "NTP install"
      yum: name={{ item }} state=present
      with_items:
        - ntp
        - chrony
        - httpd

    - name: "start and enable ntp"
      systemd: name={{ item }} state=started enabled=yes
      with_items:
        - ntpd
        - chronyd
        - httpd
