---
- hosts: REDHAT
  remote_user: root
  tasks: 
    - name: "NTP install"
      yum: name={{ item }} state=present
      with_items:
        - ntp
        - chrony
        - httpd

    - name: "start and enable ntp"
      systemd: name={{ item }} state=started enabled=yes
      with_items:
        - ntpd
        - chronyd
        - httpd

    - name: "Configuring the Chrony.conf"
      lineinfile:
        path: /etc/chrony.conf
        regexp: '^server'
        state: absent

    - name: "Configuring the Chrony.conf Time Zones"
      blockinfile:
        path: /etc/chrony.conf
        block: |
          server 0.asia.pool.ntp.org
          server 1.asia.pool.ntp.org
          server 2.asia.pool.ntp.org
          server 3.asia.pool.ntp.org
        insertafter: .# Please*

     - name: "restart and enable ntp/ chrony"
       systemd: name={{ item }} state=restarted 
       with_items:
        - ntpd
        - chronyd

      - name: "reload and enable ntp/ chrony"
        systemd: name={{ item }} state=reloaded 
        with_items:
        - ntpd
        - chronyd

